import dotenv from "dotenv";
import { join } from "path";
import { getSupabase } from "../src/db/supabase";
import type { TablesInsert } from "../src/db/types";

dotenv.config({ path: join(process.cwd(), "config/.env.local") });

type SeedTables =
  | "scripts"
  | "video_assets"
  | "experiments"
  | "published_posts"
  | "system_events";

type SeedCounts = Record<SeedTables, number>;

const supabase = getSupabase();

const now = new Date().toISOString();

const ids = {
  script: "00000000-0000-0000-0000-000000000001",
  asset: "00000000-0000-0000-0000-000000000002",
  experiment: "00000000-0000-0000-0000-000000000003",
  post: "00000000-0000-0000-0000-000000000004",
  eventStart: "00000000-0000-0000-0000-000000000101",
  eventEnd: "00000000-0000-0000-0000-000000000102",
} as const;

const scriptSeed: TablesInsert<"scripts"> = {
  script_id: ids.script,
  product_id: null,
  script_text: "This is a seeded script showcasing the ACE content pipeline.",
  hook: "Seeded hook: discover how ACE automates creativity.",
  creative_variables: {
    emotion: "curious",
    structure: "Problem-Agitate-Solution",
    style: "concise",
  },
  created_at: now,
};

const assetSeed: TablesInsert<"video_assets"> = {
  asset_id: ids.asset,
  script_id: scriptSeed.script_id,
  storage_path: "seed/video_assets/asset_1.mp4",
  thumbnail_path: "seed/video_assets/asset_1.jpg",
  duration_seconds: 30,
  created_at: now,
};

const experimentSeed: TablesInsert<"experiments"> = {
  experiment_id: ids.experiment,
  product_id: scriptSeed.product_id,
  script_id: scriptSeed.script_id,
  asset_id: assetSeed.asset_id,
  hypothesis: "Seed experiment linking script and asset",
  variation_label: "control",
  created_at: now,
};

const postSeed: TablesInsert<"published_posts"> = {
  post_id: ids.post,
  experiment_id: experimentSeed.experiment_id,
  platform: "tiktok",
  caption: "Seeded post generated by ACE experiment 1",
  platform_post_id: "external_seed_post_1",
  hashtags: ["seed", "ace", "automation"],
  posted_at: now,
  created_at: now,
};

const startEventSeed: TablesInsert<"system_events"> = {
  event_id: ids.eventStart,
  event_type: "seed.start",
  agent_name: "seed-script",
  payload: { note: "Seeding process started" },
  created_at: now,
};

const uniqueKeys = {
  scripts: "script_id",
  video_assets: "asset_id",
  experiments: "experiment_id",
  published_posts: "post_id",
  system_events: "event_id",
} as const satisfies Record<SeedTables, string>;

const counts: SeedCounts = {
  scripts: 0,
  video_assets: 0,
  experiments: 0,
  published_posts: 0,
  system_events: 0,
};

const logSeedResult = (
  table: SeedTables,
  id: string,
  created: boolean,
) => {
  const status = created ? "created" : "skipped (already exists)";
  console.log(`[${table}] ${status}: ${id}`);
};

const insertIfMissing = async <T extends SeedTables>(
  table: T,
  payload: TablesInsert<T>,
) => {
  const uniqueKey = uniqueKeys[table];
  const uniqueValue = payload[uniqueKey as unknown as keyof TablesInsert<T>];

  if (uniqueValue === undefined || uniqueValue === null) {
    throw new Error(
      `Missing unique key ${uniqueKey} for table ${table}, cannot seed.`,
    );
  }

  const { data: existing, error: selectError } = await supabase
    .from(table)
    .select(uniqueKey)
    .eq(uniqueKey as any, uniqueValue as any)
    .maybeSingle();

  if (selectError) {
    throw new Error(
      `Failed checking existing row in ${table}: ${selectError.message}`,
    );
  }

  if (existing) {
    logSeedResult(table, String(uniqueValue), false);
    return false;
  }

  // Cast payload to any to satisfy Supabase client overload typing for dynamic table names
  const { error: insertError } = await supabase.from(table).insert(payload as any);

  if (insertError) {
    throw new Error(
      `Failed inserting into ${table}: ${insertError.message}`,
    );
  }

  counts[table] += 1;
  logSeedResult(table, String(uniqueValue), true);
  return true;
};

const seedSystemEvent = async (payload: TablesInsert<"system_events">) => {
  try {
    await insertIfMissing("system_events", payload);
  } catch (error) {
    console.error("[system_events] Error during seed:", error);
    throw error;
  }
};

const seedScripts = async () => {
  try {
    await insertIfMissing("scripts", scriptSeed);
  } catch (error) {
    console.error("[scripts] Error during seed:", error);
    throw error;
  }
};

const seedVideoAssets = async () => {
  try {
    await insertIfMissing("video_assets", assetSeed);
  } catch (error) {
    console.error("[video_assets] Error during seed:", error);
    throw error;
  }
};

const seedExperiments = async () => {
  try {
    await insertIfMissing("experiments", experimentSeed);
  } catch (error) {
    console.error("[experiments] Error during seed:", error);
    throw error;
  }
};

const seedPublishedPosts = async () => {
  try {
    await insertIfMissing("published_posts", postSeed);
  } catch (error) {
    console.error("[published_posts] Error during seed:", error);
    throw error;
  }
};

const seedEndEvent = async () => {
  const endEvent: TablesInsert<"system_events"> = {
    event_id: ids.eventEnd,
    event_type: "seed.end",
    agent_name: "seed-script",
    payload: { counts },
    created_at: new Date().toISOString(),
  };

  await seedSystemEvent(endEvent);
};

const printSummary = () => {
  console.log("\nSeed summary:");
  (Object.keys(counts) as SeedTables[]).forEach((table) => {
    console.log(`- ${table}: ${counts[table]} row(s) created`);
  });
};

const main = async () => {
  console.log("Starting ACE seed...");

  await seedSystemEvent(startEventSeed);
  await seedScripts();
  await seedVideoAssets();
  await seedExperiments();
  await seedPublishedPosts();
  await seedEndEvent();

  printSummary();
};

try {
  await main();
  console.log("Seed completed successfully.");
  process.exit(0);
} catch (error) {
  console.error("Seed failed:", error);
  process.exit(1);
}
